server:
  port: 8080
spring:
  graphql:
    schema:
      locations: classpath:/graphql/
  config:
    import: optional:nacos:application.yml
  application:
    name: mytube-gateway-graphql
  data:
    redis:
      host: www.serein.com
      port: 6379
      password: redis_6KtBtd
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      server-addr: www.serein.com:8848
      username: nacos
      password: nacos
dubbo:
  application:
    name: mytube-gateway-graphql
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}?username=nacos&password=nacos
    parameters:
      enable-empty-protection: true
      register-consumer-url: true
