server:
  port: 8103
spring:
  config:
    import: optional:nacos:application.yml
  application:
    name: mytube-comment-service
  datasource:
    url: jdbc:postgresql://www.serein.com:5432/mytube
    username: user_D27Hrf
    password: password_Rh7CzX
    driver-class-name: org.postgresql.Driver
  cloud:
    nacos:
      server-addr: www.serein.com:8848
      config:
        import-check:
          enabled: false
      username: nacos
      password: nacos
dubbo:
  application:
    name: mytube-comment-service
  registry:
    address: nacos://${spring.cloud.nacos.server-addr}
  protocol:
    name: dubbo
    port: -1
