server:
  port: 8108
spring:
  config:
    import: optional:nacos:application.yml
  application:
    name: mytube-upload-service
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      server-addr: www.serein.com:8848
      username: nacos
      password: nacos
directory:
  cover: data/cover
  video: data/video
  chunk: data/chunk
dubbo:
  application:
    name: mytube-upload-service
  registry:
    address: ${spring.cloud.nacos.config.server-addr}
  protocol:
    name: dubbo
    port: -1

minio:
  endpoint: http://www.serein.com:9000
  accessKey: minio_tyaBYX
  secretKey: minio_RW4Wsj
  bucket: mytube
s3:
  endpoint: http://www.serein.com:9300
  accessKey: rustfsadmin
  secretKey: rustfsadmin_JprDWy
  bucket: mytube
