server:
  port: 8108
spring:
  config:
    import: optional:nacos:application.yml
  application:
    name: mytube-upload-service
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
      server-addr: www.serein.com:8848
      username: nacos
      password: nacos
dubbo:
  application:
    name: mytube-upload-service
  registry:
    address: ${spring.cloud.nacos.config.server-addr}
  protocol:
    name: dubbo
    port: -1
